version: '{branch}-{build}'

environment:
  QTDIR: C:\Qt\5.7\mingw53_32

install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - C:\Qt\5.7\mingw53_32\bin\qtenv2.bat

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - qmake -r
  - mingw32-make
